const actions = {
    UPDATE_INPUT: 'UPDATE_INPUT',
    TOGGLE_MATCH_CASE: 'TOGGLE_MATCH_CASE',
    INCREMENT_CARET: 'INCREMENT_CARET',
    DECREMENT_CARET: 'DECREMENT_CARET',
}

export default actions;
